### PR TITLE
Update Links functionality

### PR DESCRIPTION
**Pull request by riusricardo**
Removes unused LinksNFT contract
Upgrades Links to handle NFTs, ERC20 and xDai/Eth

### CODE REVIEW

**Comment by TimDaub** [comment]
Hi @riusricardo, thanks for this contribution. It'd be helpful if you could give a bit of context on what's happening in this PR and what your future plans with the Link functionality are.

As far as I understood, you're adding NFT, ERC20 and xDAI/ETH support to the Link contract.
I'm also assuming that we need to deploy this update to the chain, correct?

As it handles money directly via the contract, how do you recommend we have it reviewed and vetted for potential security issues?

Thanks!

**Comment by riusricardo** [comment]
@TimDaub This PR is an enhancement on all my previous work on the Links contracts.

You're right, it adds the functionality to send tokens and not only xDAI. However this is the first step of a bigger upgrade. In other words, it will enable the usage and transfer of tokens if you have xDai to pay the transaction fee.
It has breaking changes because it adds a new parameter to the function, so it requires a new contract deployment.

The next part of the upgrade is to create a glue layer to add compatibility between the tokens and Tanookey's gas station to enable token MetaTxs.

About the security,  it has the same security guarantees that I have been using all the time since we integrated the functionality into the Burner Wallet (mutex to prevent reentrancy, safe transfer funtions)

**Comment by johannbarbie** [comment]
side question, if i may.

the way i understand the links contract is this:
1. sender -> funds -> links contract
2. sender -> privateKey + nonce -> receiver
3. receiver -> sig -> links contract
4. links contract -> funds -> receiver

why is the contract needed to park money at all? why not use a private key for it like this:
1. sender -> funds -> priv
2. sender -> privateKey -> receiver
3. receiver -> funds -> receiver

the sender wallet could monitor the address of the privateKey generated for the link, and if expiration time passed, just send the funds back to itself, no?

**Comment by riusricardo** [comment]
> why is the contract needed to park money at all? why not use a private key for it like this:

@johannbarbie This is a valid point and has been discussed a few times in the past. The expiration is the main reason to use this contract. [POA Forum](https://forum.poa.network/t/how-does-burner-wallets-send-to-link-work/2090)

> the sender wallet could monitor the address of the privateKey generated for the link, and if expiration time passed, just send the funds back to itself, no?

This idea will add more load to the wallet and opens a security breach. There is an issue on finding a better way to store the private key. This could become a bigger issue. Your wallet will be storing many private keys and monitoring many different expiration dates if you decide to use the functionality a few times.

There is a measure in place that will enhance the UX without compromising security by storing all the keys. We will store some data on the Bloom filter log using events; this will create a cheap way of creating a recovery mechanism after links expiration.

**Comment by TimDaub** [comment]
Hi @riusricardo, sorry for taking so long. I've just changed the base as we discussed in Telegram.
´upgrade_contracts` is in sync with current master, so you'll probably have to rebase a bunch of stuff.

Again, sorry for that!

**Comment by riusricardo** [comment]
Closing in favor of a full OpenZeppelin's GSN upgrade.

**Pull request closed without merging**
