### PR TITLE
Enhance CSS and add Help section

### PR DESCRIPTION
**Pull request by starkblaze01**
Issue #5 ,
Add reactstrap to give a better look, and add Modals from reactstrap to create Help section where instructions can be given.
screenshot from 2018-11-17 04_00_54
screenshot from 2018-11-17 04_03_21
screenshot from 2018-11-17 04_00_27
screenshot from 2018-11-17 03_56_57

### CODE REVIEW

**Comment by starkblaze01** [comment]
WIP
This the basic theme I can think of. If you like it I can make more changes and bring all the Send options in a drop-down or a Navbar. I have made a few changes in QRCodeScanner changing the position of Scanner and close option also.

**Comment by austintgriffith** [comment]
We have forked away from this version so I'll close this because of merge conflicts. Thanks for looking into it!

**Comment by starkblaze01** [comment]
@austintgriffith , should I send new PR ?

**Comment by austintgriffith** [comment]
Not yet, basically, we need to decide on our favorite UI over in https://github.com/austintgriffith/burner-wallet/issues/5 first and then we can spec out the build to integrate it.

**Pull request closed without merging**
