### PR TITLE
Module scavenger hunt for hackathon

### PR DESCRIPTION
**Pull request by eccheung4**
This is still Work in Progress.  Just submitting for the hackathon.

ScavengerHunt contract is done for the most part, just still need to hook up the UI to the contract.
Need owner view and user view.
Hard coded to 5 questions with contract deployment, Answers ["zero", "one", "two", "three", "four"]

Basic flow:
Deploy contract with answers and gameEndTime and revealEndTime
On deployment game starts:
CommitPhase: User can commitAnswer for any question.
After gameEndTime, Owner needs to call endGame with his answer and salt
RevealPhase: Then users can revealAnswers
After revealEndTime: Anyone can call findWinner, which will find winner and send them whatever balance the contract has.

### CODE REVIEW

**Comment by austintgriffith** [comment]
Actually, let's merge this into a branch. 
I just created a 'scavengerhunt' branch. 
Mind merging there?

**Comment by austintgriffith** [comment]
https://github.com/austintgriffith/burner-wallet/tree/scavengerhunt

**Comment by owocki** [comment]
hey, is there a video of the demo or anything i can checkout/

**Comment by eccheung4** [comment]
@owocki Sorry, I don't have a video of demo, but I could create one later.  Most work was done in the smart contract and playing around with it in remix.  After I felt the contract was working ok in remix, I ran out of time hooking everything up with the UI.  I'll see if I can finish hooking it up with UI this weekend.

**Comment by owocki** [comment]
cool cool.  yea the video might help people make sense of the work without having to comb through the code.

**Comment by eccheung4** [comment]
@owocki sorry, it took some time, but here is video and some docs:
Youtube: https://www.youtube.com/watch?v=QiLhA6UIp5Y
User flow: https://docs.google.com/document/d/1RfJO8b5yCu9aPOycsq3J2l9KwHVJhnG_TySUrJ5WgnE/edit?usp=sharing
Initial Ideas: https://docs.google.com/document/d/1jTkQ3yp0fkuqrLrW7CDbE2pto5R-3RjD-FhECSpvBaE/edit?usp=sharing

**Comment by eccheung4** [comment]
also branch with updated code: https://github.com/eccheung4/burner-wallet/tree/scavengerhunt-dev-ui

**Comment by mkosowsk** [comment]
@eccheung4 Amazing!!! 👍

**Pull request closed without merging**
