### PR TITLE
Fix: Implement internationalization library so Burner displays in cor…

### LINKED ISSUE #76: Implement internationalization library so Burner displays in correct language
In order to help with widespread adoption the Burner will need to be translated to multiple languages.

Let's start by implementing an i18n library for all the buttons and text. 

This one looks okay, but if you know of a better one, please use it.
https://github.com/i18next/react-i18next

### PR DESCRIPTION
**Pull request by iamonuwa**
…rect language

Fixes #76

### CODE REVIEW

**Comment by dbe** [comment]
@iamonuwa Why are all of the file permissions changed from 100644 -> 100755?

**Comment by iamonuwa** [comment]
I'll revert the permissions. 

> @iamonuwa Why are all of the file permissions changed from 100644 -> 100755?

installing npm packages didn't work for me. I'll revert it to 644

**Comment by dbe** [comment]
Ah ok. I just want to avoid changing those if we don't need. But if there is some issue, we can attempt to solve it. Did you figure out why installing the npm packages didn't work? Ideally it shouldn't require file permissions to be set any given way as far as I know.

**Comment by iamonuwa** [comment]
> Ah ok. I just want to avoid changing those if we don't need. But if there is some issue, we can attempt to solve it. Did you figure out why installing the npm packages didn't work? Ideally it shouldn't require file permissions to be set any given way as far as I know.

All my investigations pointed to the permission thing

**Comment by iamonuwa** [comment]
@dbe Looks like I can't fix the permission here. Can you update it?

**Comment by dbe** [comment]
@iamonuwa Sure

**Comment by dbe** [comment]
Ok, looks like file permissions are back to normal. 

Time to go about review as normal :p

**Comment by iamonuwa** [comment]
Thank you @dbe

**Comment by dbe** [comment]
Ok cool, looks like we are up to date with master, and the project is loading locally for me.

@iamonuwa Can you explain how this integration works, and what we need to keep in mind going forward as we add more content?

Also, how do I pull up the site in another language? Say Spanish for example? Is that possible now, or do we need to add more custom internationalization code for that to work?

**Comment by iamonuwa** [comment]
You can manually translate the values of each of the keys in the en.json to suit the new language

**Comment by iamonuwa** [comment]
There is no additional customization. Everything is ready and good to go.

**Comment by jtremback** [comment]
What's going on with this? This is high priority for us at www.althea.org. We can contribute a Spanish localization when it's merged.

**Comment by dbe** [comment]
@jtremback Cool, I'll get it merged in.

Are you guys running your own version of this, or are you relying on these changes being deployed to xdai.io as well?

**Comment by dbe** [comment]
Actually, running into some weird stuff that seems to be unrelated to this branch, so I'm going to leave it to @austintgriffith to make the final call on merging this one in. 

I got it up to date with master, so no more merge conflicts.

**Comment by jtremback** [comment]
@dbe we will probably run a fork of burner wallet, since we have no need of the vendor features, probably have a different view on security/private key recovery, will be doing a redesign, etc. We'll contribute a Spanish localization and then fork at the point that it's merged.

**Comment by austintgriffith** [comment]
Okay deployed the Spanish version thanks to Eduardo to https://s.xdai.io (stage). Not sure if it's working yet but there should be an en and es version: https://github.com/austintgriffith/burner-wallet/blob/master/src/i18n/locales/es.json

**Pull request merged**
