### PR TITLE
Add ERC 721 component

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #186

### CODE REVIEW

**Comment by iamonuwa** [comment]
> Some high level feedback (mostly copied from #184):
> 
> * Please name `.sol` and module files according to what they do and not `mycontract`
> * Please don't commit large sections of commented code
> * Please remove `HARDCODEDVIEW` value before requesting review of PR
> * Please use i18n where ever you can
> * Integrate module into existing components and keep changesets small ideally (e.g. Badge.js) (not required but easier to approve for me)

Coming back to this after so long

I had to revert the PR to get the `YourModule component` which I reused earlier without making a copy. For the commented code, its part of `YourModule component` which needs to be there. I did not use any `.sol` file. I had to return the solidity file for YourModule component.

**Comment by austintgriffith** [comment]
I haven't tested anything yet, let me just merge it in because we created this branch for you and test it there. It might take me a couple days.

**Comment by austintgriffith** [comment]
wasn't there a gitcoin bounty that went with this? I can't find it. Do I owe you?

**Comment by iamonuwa** [comment]
> wasn't there a gitcoin bounty that went with this? I can't find it. Do I owe you?

https://gitcoin.co/issue/austintgriffith/burner-wallet/160/2947

**Pull request merged**
