### PR TITLE
Add react router

### PR DESCRIPTION
**Pull request by dmihal**
Reissuing #144

### CODE REVIEW

**Comment by TimDaub** [comment]
Hi @dmihal 👋

There's awesome stuff in this PR. In particular, I see the following things happening:

- creating a config.js
- refactoring RecentTransactions into a TransactionStore
- add react-router-dom.

To speed up the review, I'd suggest however that we look at the above mentioned pieces individually. Would you mind splitting them up into individual PRs?

Regarding config.js, we've done something very similar here: https://github.com/leapdao/burner-wallet/blob/master/src/config.js

Right now, I'd prefer our solution to the one proposed here as it
- takes into account most magic constants in the code (e.g. we've taken them out of Exchange.js)
- generically renames the constants and groups them (e.g. SIDECHAIN and ROOTCHAIN).
- doesn't overwrite already defined constants based on location (e.g. POA_XDAI_NODE).

If you don't mind, I'd prepare a PR for changing config.js and sending it here soon for e.g. you to review. Thoughts?

**Comment by dmihal** [comment]
Hey @TimDaub 

This PR was recreating #144, which got removed from master after a big rollback before one of the burner events.

Looks like a couple of the other PRs I made back then got swept up in this one (TransactionStore, config.js).

At this point I'm mostly focusing on building the new structure for the burner wallet. Rebasing those old PRs into the current master was a bit difficult and I don't think i have the time to focus on splitting apart those old PRs.

Right now I'm open to either letting this PR close or someone else take over this task, but open to other thoughts.

**Comment by TimDaub** [comment]
@dmihal OK, no problem! I'll take care of it then.

**Comment by TimDaub** [comment]
I was thinking whether or not to simply untangle this PR myself today but then I became hesitant about the time that would be required. I'm also unsure about having this functionality in master, given that we're now working according to _the_ spec. So I've decided to do the following:

- I've created #215. It's goal is to extract react-router-dom functionality from this PR
- I've left it open for now what to do with config.js and TransactionStore.
- As this branch will hopefully life on in your fork, and since so far no drastic changes to `RecentTransactions.js` have been planned, I think it's safe to think about this again after we've done #209 "Minimal integration of burner-core into burner-wallet".

@dmihal if you have a better idea, please let me know.

**Pull request closed without merging**
