### PR TITLE
Initial support for Relay Hub

### PR DESCRIPTION
**Pull request by alex-forshtat-tbk**
1. Make 'Links' contract implement 'RelayRecipient'. This allows
relays to query its 'accept_relayed_call' method and see if it
is ready to accept the call. Current implementation of
'accept_relayed_call' validates that the call is done to a 'claim'
method and that this is a valid claim.

2. Add another step to 'clevis test full'. The 'Links' contract must
make a deposit in the 'RelayHub' in order to pay the relayers for the
gas used by clients.

3. In 'relayClaim' instead of making an HTTP request to a hard-coded
relay URL, pass the encoded function call to 'gasless' module.

### CODE REVIEW

**Comment by riusricardo** [comment]
Before merging this, some audit needs to be done to your solidity libraries. 
I took a fast look and saw some hardcoded ETH values that could create some restrictions.

@alex-forshtat-tbk  Can you continue developing your idea or are this all the changes in your proposal?

**Comment by drortirosh** [comment]
> Before merging this, some audit needs to be done to your solidity libraries.
> I took a fast look and saw some hardcoded ETH values that could create some restrictions.

Not sure what you mean by "hard-coded ETH values"
We do set `txfee`, which is our parameter to say how much fee (in %) we agree to pay. in this case 12 means, we agree to pay 112% of the actual gas price.
We also set `gas_limit`, but that should be optional (can use default gas estimation)

**Comment by riusricardo** [comment]
@drortirosh Thanks for replying. I saw some limits in: 
https://github.com/tabookey/tabookey-gasless/blob/master/contracts/RelayHub.sol#L14#L15
I know that it is a deposit that the relay should cover. I just wanted to know if there are no more changes for this PR which involves many new pieces.

**Comment by drortirosh** [comment]
Oh, yes.
The RelayHub is still in alpha, and there might be some tweaks to be done to these parameters.
Still, it is working (on local network, and on ropsten)
e.g. the relay is required to have at least 0.5eth to *register*, so we know it has enough balance for some future calls (it has to re-register daily)
the `low-ether` is obsolete

**Comment by austintgriffith** [comment]
So are we at a point with this that we can merge it in and start playing around with it, or is it still in a dev phase?

**Comment by yoav-tabookey** [comment]
You can start playing with it immediately and see how it works, but it's
currently on testnet with a couple of registered relays. There is no
RelayHub on mainnet yet. We're working towards that.

**Comment by riusricardo** [comment]
This SCs will need to be deployed in the xDai chain. I think that the best way to proceed will be to merge it into another parallel branch, not to the master branch.

**Comment by yoav-tabookey** [comment]
I agree. I was chatting about that with Dror. Let's merge it as a separate
branch for now, so you can start experimenting with the decentralized
network or relays without having an effect on your production code. You
should be able to demo it easily, and once it's on mainnet we can merge.

BTW note that your contract doesn't become dependent on RelayHub. Your code
never calls into RelayHub. RelayHub always calls you, so it's a one way
flow.

**Comment by alex-forshtat-tbk** [comment]
> This SCs will need to be deployed in the xDai chain. I think that the best way to proceed will be to merge it into another parallel branch, not to the master branch.
> Just to keep it with the Ethereum "Out of an Abundance of Caution" approach.

Yes, that sounds good. So which branch should I merge this into, then? By the way, I do not have a write permission to this repository, so I cannot create a new one myself.

**Comment by riusricardo** [comment]
> > This SCs will need to be deployed in the xDai chain. I think that the best way to proceed will be to merge it into another parallel branch, not to the master branch.
> > Just to keep it with the Ethereum "Out of an Abundance of Caution" approach.
> 
> Yes, that sounds good. So which branch should I merge this into, then? By the way, I do not have a write permission to this repository, so I cannot create a new one myself.

It's @austintgriffith's call. I think that he is the only one with write permissions. 
Until then, you can keep working in your branch and keep it in sync with burner master. Austin could then add your repo as remote/upstream and create a new branch as he did for the **new-vend** branch.

**Comment by austintgriffith** [comment]
Are we moving this to its own branch? Should I just close this issue?

**Comment by alex-forshtat-tbk** [comment]
> Are we moving this to its own branch? Should I just close this issue?
Right, I think it is fine to merge this PR into this branch. We have a running instance of a Burner Wallet built from this branch that just works, with a gsn deployed on xdai, you can check it at:
http://burnerwithrelays2.s3-website.eu-west-2.amazonaws.com/
What do you think, should I rebase it into a master branch?

**Pull request merged**
