### PR TITLE
Attempt to evaluate a gas price before relaying a call

### PR DESCRIPTION
**Pull request by alex-forshtat-tbk**
I believe this is a safer way to estimate gas price, even though the "web3.eth.getGasPrice" is not reliable in xdai network, the relays will rely on it anyways.
P.S. I did not test this change thoroughly, still having issues just running Burner Wallet.

### CODE REVIEW

**Comment by riusricardo** [comment]
I agree on this. There is an issue rooted on 0 Txs avg in gas calculation.

https://github.com/paritytech/parity-ethereum/issues/9795

**Comment by riusricardo** [comment]
@alex-forshtat-tbk @shahafn the latest commit looks to be a misunderstanding in the code.
msg.sender is used to log the fund creator not the claimer which should not be the relay.

**Comment by drortirosh** [comment]
get_sender() helper function returns msg.sender when the transaction is
called directly. When called through a relay, it returns the real sender
(as the transaction sender is the relay)

**Comment by riusricardo** [comment]
@drortirosh Great! Thanks for clarifying. So it looks good to have it. Specially for sending tokens.

**Comment by shahafn** [comment]
@riusricardo Another issue that should be noted: RelayRecipient.sol should be on top of the inheritance hierarchy, since if Links.sol calls Vault.sol's functions that might use msg.sender in a relayed call, they should be replaced with get_sender() as well.

**Comment by riusricardo** [comment]
@shahafn that sounds good to me. I kept Vault as the the most base-like because is the one that handles the value. But if you need to change the order feel free to do it.

**Pull request merged**
